rails_4_in_action/ticketee/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'application/index'
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

end

rails_4_in_action/ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  #has_many :tickets, dependent: :destroy

  has_many :tickets, dependent: :delete_all

end

rails_4_in_action/ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
end

rails_4_in_action/ticketee/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

rails_4_in_action/ticketee/app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end

end

rails_4_in_action/ticketee/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description)
  end

end

rails_4_in_action/ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_4_in_action/ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  # def new
  #   @project = Project.new
  # end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end

  def show
    #@project = Project.find(params[:id])
  end

  def edit
    #@project = Project.find(params[:id])
  end

  def update
    #@project = Project.find(params[:id])

    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  # def destroy
  #   #@project = Project.find(params[:id])
  #   @project.destroy
  #   flash[:notice] = "Project has been deleted."
  #   redirect_to projects_path
  # end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

end

rails_4_in_action/ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show

  end

  def edit

  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :description)
  end


  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

end

rails_4_in_action/ticketee/app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

rails_4_in_action/ticketee/app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

rails_4_in_action/ticketee/app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

rails_4_in_action/ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

rails_4_in_action/ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

rails_4_in_action/ticketee/app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
    </header>

    <p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
      <li>Links will go here. Soon.</li>
    </ul>
  </div>
</div>

rails_4_in_action/ticketee/app/views/admin/projects/index.html.erb
<% admins_only do %>
    <ul class="actions">
      <li>
        <%= link_to "New Project", new_admin_project_path, class: "new" %>
      </li>
    </ul>
<% end %>

rails_4_in_action/ticketee/app/views/tickets/_form.html.erb
<%= simple_form_for([project, ticket]) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: "btn-primary" %>
<% end %>

rails_4_in_action/ticketee/app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit Ticket
    <small><%= @project.name %></small>
  </h1>
</header>
<%= render "form", project: @project, ticket: @ticket %>

rails_4_in_action/ticketee/app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

rails_4_in_action/ticketee/app/views/tickets/show.html.erb
<div id="ticket">
  <header>
    <h1><%= @project.name %></h1>
  </header>
  <header>
    <h2><%= @ticket.name %></h2>
  </header>
  <table id="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @ticket.author.email %></td>
    </tr>
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
    </tr>
  </table>
  <%= simple_format(@ticket.description) %>

  <li><%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
                  data: { confirm: "Are you sure you want to delete this ticket?"},
                  class: "delete" %></li>
</div>